<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1"/><PackageReference Include="xunit.v3" Version="3.2.1"/><PackageReference Include="xunit.runner.visualstudio" Version="3.1.5"/><ProjectReference Include="../../src/GManager.Client.Domain/GManager.Client.Domain.csproj"/><ProjectReference Include="../../src/GManager.Client.Protocol/GManager.Client.Protocol.csproj"/><ProjectReference Include="../../src/GManager.Client.Service/GManager.Client.Service.csproj"/></ItemGroup></Project>
