package com.game_manager.gm.reservation;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.game_manager.gm.catalog.*;import com.game_manager.gm.common.security.Role;import com.game_manager.gm.user.*;import com.game_manager.gm.workinghours.*;
import java.math.BigDecimal;import java.time.*;import java.util.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;import testsupport.DatabaseCleaner;import tools.jackson.databind.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class RecurrenceIntegrationTest {
 @Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired CatalogRepository catalog;@Autowired WorkingHoursRepository hours;@Autowired PasswordEncoder encoder;@Autowired JdbcTemplate jdbc;private final ObjectMapper mapper=new ObjectMapper();private static final ZoneId ZONE=ZoneId.of("Europe/Belgrade");
 @BeforeEach void clean(){DatabaseCleaner.clean(jdbc);}

 @Test void monthlyPreviewPreservesLocalRuleAcrossMonthAndDstAndBatchIsIdempotent()throws Exception{User customer=user(Role.CUSTOMER),owner=user(Role.OWNER),employee=user(Role.EMPLOYEE);CatalogItem item=service();configure(DayOfWeek.SUNDAY);configure(DayOfWeek.WEDNESDAY);Instant start=ZonedDateTime.of(LocalDate.of(2027,1,31),LocalTime.of(10,0),ZONE).toInstant();String token=login(customer),body=body(item,employee,start,"MONTHLY",1,3,"ALL_OR_NOTHING");
  JsonNode preview=node(mvc.perform(post("/api/v1/reservations/recurrence/preview").header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andReturn());
  assertThat(localDate(preview.at("/occurrences/0/startTime").asText())).isEqualTo(LocalDate.of(2027,1,31));assertThat(localDate(preview.at("/occurrences/1/startTime").asText())).isEqualTo(LocalDate.of(2027,2,28));assertThat(localDate(preview.at("/occurrences/2/startTime").asText())).isEqualTo(LocalDate.of(2027,3,31));
  String key=UUID.randomUUID().toString();MvcResult first=mvc.perform(post("/api/v1/reservations/recurrence").header("Authorization",bearer(token)).header("Idempotency-Key",key).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(header().string("Idempotency-Replayed","false")).andReturn();JsonNode created=node(first);
  mvc.perform(post("/api/v1/reservations/recurrence").header("Authorization",bearer(token)).header("Idempotency-Key",key).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(header().string("Idempotency-Replayed","true"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM reservations",Integer.class)).isEqualTo(3);
  JsonNode occurrence=created.at("/created/0");mvc.perform(patch("/api/v1/reservations/{id}/status",occurrence.get("id").asText()).header("Authorization",bearer(login(owner))).contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"CANCELLED\",\"reason\":\"Samo ovaj termin\",\"version\":"+occurrence.get("version").asLong()+"}")).andExpect(status().isOk());
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM reservations WHERE recurrence_series_id=? AND status='CANCELLED'",Integer.class,created.get("seriesId").asText())).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM reservations WHERE recurrence_series_id=? AND status='PENDING'",Integer.class,created.get("seriesId").asText())).isEqualTo(2);
 }

 @Test void partialConflictsAreExplicitAndLimitsRejectUnboundedGeneration()throws Exception{User customer=user(Role.CUSTOMER),employee=user(Role.EMPLOYEE);CatalogItem item=service();LocalDate monday=LocalDate.now().plusDays(30).with(java.time.temporal.TemporalAdjusters.nextOrSame(DayOfWeek.MONDAY));configure(DayOfWeek.MONDAY);Instant start=ZonedDateTime.of(monday,LocalTime.of(10,0),ZONE).toInstant();String token=login(customer);
  reserve(token,item,employee,start.plus(7,java.time.temporal.ChronoUnit.DAYS));String skip=body(item,employee,start,"WEEKLY",1,3,"SKIP_CONFLICTS");JsonNode result=node(mvc.perform(post("/api/v1/reservations/recurrence").header("Authorization",bearer(token)).header("Idempotency-Key",UUID.randomUUID()).contentType(MediaType.APPLICATION_JSON).content(skip)).andExpect(status().isCreated()).andReturn());assertThat(result.get("created").size()).isEqualTo(2);assertThat(result.get("skipped").size()).isEqualTo(1);
  int before=jdbc.queryForObject("SELECT COUNT(*) FROM reservations",Integer.class);mvc.perform(post("/api/v1/reservations/recurrence").header("Authorization",bearer(token)).header("Idempotency-Key",UUID.randomUUID()).contentType(MediaType.APPLICATION_JSON).content(body(item,employee,start,"WEEKLY",1,3,"ALL_OR_NOTHING"))).andExpect(status().isConflict());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM reservations",Integer.class)).isEqualTo(before);
  mvc.perform(post("/api/v1/reservations/recurrence").header("Authorization",bearer(token)).header("Idempotency-Key",UUID.randomUUID()).contentType(MediaType.APPLICATION_JSON).content(body(item,employee,start.plus(28,java.time.temporal.ChronoUnit.DAYS),"WEEKLY",1,21,"SKIP_CONFLICTS"))).andExpect(status().isBadRequest());
  mvc.perform(post("/api/v1/reservations/recurrence/preview").header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content(body(item,employee,start,"MONTHLY",4,20,"SKIP_CONFLICTS"))).andExpect(status().isBadRequest());
 }

 private void reserve(String token,CatalogItem item,User employee,Instant start)throws Exception{mvc.perform(post("/api/v1/reservations").header("Authorization",bearer(token)).header("Idempotency-Key",UUID.randomUUID()).contentType(MediaType.APPLICATION_JSON).content("{\"serviceId\":\""+item.getId()+"\",\"employeeId\":\""+employee.getId()+"\",\"startTime\":\""+start+"\"}")).andExpect(status().isCreated());}
 private String body(CatalogItem item,User employee,Instant start,String frequency,int interval,int occurrences,String policy){return "{\"serviceId\":\""+item.getId()+"\",\"employeeId\":\""+employee.getId()+"\",\"startTime\":\""+start+"\",\"frequency\":\""+frequency+"\",\"interval\":"+interval+",\"occurrences\":"+occurrences+",\"conflictPolicy\":\""+policy+"\"}";}
 private void configure(DayOfWeek day){WorkingHours value=hours.findByDayOfWeek(day).orElseThrow();value.setActive(true);value.setOpenTime(LocalTime.of(8,0));value.setCloseTime(LocalTime.of(18,0));hours.saveAndFlush(value);}
 private CatalogItem service(){CatalogItem value=new CatalogItem();value.setName("Recurring service");value.setType(ItemType.SERVICE);value.setPrice(BigDecimal.TEN);value.setDurationMinutes(60);value.setActive(true);return catalog.saveAndFlush(value);}
 private User user(Role role){return users.saveAndFlush(new User(role.name(),role+"-recurrence-"+UUID.randomUUID()+"@example.test",encoder.encode("StrongPass1!"),role,true,null));}
 private String login(User user)throws Exception{return node(mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+user.getEmail()+"\",\"password\":\"StrongPass1!\"}")).andExpect(status().isOk()).andReturn()).get("token").asText();}
 private JsonNode node(MvcResult result){return mapper.readTree(result.getResponse().getContentAsByteArray());}private String bearer(String token){return "Bearer "+token;}private LocalDate localDate(String instant){return Instant.parse(instant).atZone(ZONE).toLocalDate();}
}
