package com.game_manager.gm.ai;

import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
import com.game_manager.gm.ai.dto.*;import com.game_manager.gm.audit.AuditWriter;import com.game_manager.gm.common.error.ApplicationException;import com.game_manager.gm.common.security.*;import com.game_manager.gm.feature.*;import com.game_manager.gm.report.ReportService;import io.micrometer.core.instrument.simple.SimpleMeterRegistry;import java.net.URI;import java.time.*;import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.http.HttpStatus;
class AiSummaryServiceTest {ReportService reports=mock(ReportService.class);CurrentUserProvider users=mock(CurrentUserProvider.class);FeatureFlagService flags=mock(FeatureFlagService.class);AiSummaryProvider provider=mock(AiSummaryProvider.class);AiUsageRepository usage=mock(AiUsageRepository.class);AuditWriter audit=mock(AuditWriter.class);UUID owner=UUID.randomUUID(),report=UUID.randomUUID();AiSummaryService service;
 @BeforeEach void setup(){AiProperties config=new AiProperties("http",URI.create("https://ai.example/v1"),"secret","model",100,200,100,1000,2,60,90);service=new AiSummaryService(reports,users,flags,provider,usage,config,audit,new SimpleMeterRegistry(),Clock.fixed(Instant.parse("2026-08-10T10:00:00Z"),ZoneOffset.UTC));when(users.requireCurrentUser()).thenReturn(new AuthenticatedUser(owner,"owner@example.com",Role.OWNER));when(flags.enabled(FeatureFlag.AI_ASSISTANT,owner)).thenReturn(true);when(usage.tokensSince(eq(owner),any())).thenReturn(0L);when(reports.aiSummarySource(report)).thenReturn(new ReportService.AiSummarySource(report,owner,"orders",42,Instant.parse("2026-08-10T09:00:00Z")));}
 @Test void returnsAuditedNonAiFallbackWhenProviderFails(){when(provider.summarize(any())).thenThrow(new AiProviderException("timeout"));AiReportSummaryResponse result=service.summarize(report,new AiSummaryRequest(true));assertThat(result.aiGenerated()).isFalse();assertThat(result.sources()).singleElement().extracting(AiReportSummaryResponse.Source::reportId).isEqualTo(report);verify(usage).saveAndFlush(any());verify(audit).write(eq("AI_REPORT_SUMMARY_USED"),eq("AI_USAGE"),any(),isNull(),anyMap(),isNull(),any());}
 @Test void neverCallsProviderWhenPermissionScopedReportLookupFails(){when(reports.aiSummarySource(report)).thenThrow(new ApplicationException(HttpStatus.NOT_FOUND,"Report not found"));assertThatThrownBy(()->service.summarize(report,new AiSummaryRequest(true))).isInstanceOf(ApplicationException.class);verifyNoInteractions(provider);}
 @Test void enforcesConsentKillSwitchAndDailyCostCap(){assertThatThrownBy(()->service.summarize(report,new AiSummaryRequest(false))).isInstanceOf(ApplicationException.class);when(flags.enabled(FeatureFlag.AI_ASSISTANT,owner)).thenReturn(false);assertThatThrownBy(()->service.summarize(report,new AiSummaryRequest(true))).isInstanceOf(ApplicationException.class);when(flags.enabled(FeatureFlag.AI_ASSISTANT,owner)).thenReturn(true);when(usage.tokensSince(eq(owner),any())).thenReturn(1000L);assertThatThrownBy(()->service.summarize(report,new AiSummaryRequest(true))).isInstanceOf(ApplicationException.class);verifyNoInteractions(provider);}
}
