services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: gmanager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - gmanager_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ugmanager", "-pgmanager"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  gmanager_mysql:
