package com.game_manager.gm.machine;
import com.game_manager.gm.auth.RateLimitService;import com.game_manager.gm.common.error.ApplicationException;import com.game_manager.gm.common.security.Role;import com.game_manager.gm.gamingsession.*;import com.game_manager.gm.gamingsession.command.*;import com.game_manager.gm.machine.dto.MachineDtos.*;import com.game_manager.gm.security.JwtService;import com.game_manager.gm.station.*;import com.game_manager.gm.user.*;import java.security.*;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class MachineProtocolService {
 private final StationEnrollmentTokenRepository tokens;private final StationMachineIdentityRepository identities;private final StationAuthChallengeRepository challenges;private final StationHeartbeatRepository heartbeats;private final GamingStationProfileRepository stations;private final GamingSessionRepository sessions;private final StationCommandRepository commands;private final MachinePrincipalProvider principal;private final JwtService jwt;private final RateLimitService limits;private final Clock clock;private final UserRepository users;private final PasswordEncoder passwords;private final MachineLoginAttemptWriter loginAttempts;private final SecureRandom random=new SecureRandom();
 public MachineProtocolService(StationEnrollmentTokenRepository t,StationMachineIdentityRepository i,StationAuthChallengeRepository c,StationHeartbeatRepository h,GamingStationProfileRepository s,GamingSessionRepository gs,StationCommandRepository sc,MachinePrincipalProvider p,JwtService jwt,RateLimitService limits,Clock clock,UserRepository users,PasswordEncoder passwords,MachineLoginAttemptWriter loginAttempts){tokens=t;identities=i;challenges=c;heartbeats=h;stations=s;sessions=gs;commands=sc;principal=p;this.jwt=jwt;this.limits=limits;this.clock=clock;this.users=users;this.passwords=passwords;this.loginAttempts=loginAttempts;}

 @Transactional public EnrollResponse enroll(EnrollRequest request){Instant now=clock.instant();StationEnrollmentToken token=tokens.findByHashForUpdate(MachineCrypto.hash(request.enrollmentToken())).orElseThrow(this::invalidEnrollment);
  limits.checkMachine(token.getStationId(),"enroll");
  if(token.getStatus()!=EnrollmentTokenStatus.ACTIVE||!token.getExpiresAt().isAfter(now))throw invalidEnrollment();GamingStationProfile station=stations.findByResourceId(token.getStationId()).filter(GamingStationProfile::isClientEnabled).orElseThrow(this::invalidEnrollment);
  PublicKey key;try{key=MachineCrypto.publicKey(request.publicKeyBase64());}catch(IllegalArgumentException e){throw new ApplicationException(HttpStatus.BAD_REQUEST,e.getMessage());}String fingerprint=MachineCrypto.fingerprint(key);if(identities.existsByPublicKeyFingerprint(fingerprint))throw new ApplicationException(HttpStatus.CONFLICT,"Machine public key is already enrolled");
  List<StationMachineIdentity> existing=identities.findByStationIdOrderByKeyVersionDesc(token.getStationId());boolean active=existing.stream().anyMatch(this::valid);
  if(token.getPurpose()==EnrollmentPurpose.INITIAL&&active||token.getPurpose()==EnrollmentPurpose.ROTATION&&!active)throw invalidEnrollment();long version=existing.stream().mapToLong(StationMachineIdentity::getKeyVersion).max().orElse(0)+1;
  if(token.getPurpose()==EnrollmentPurpose.ROTATION)for(StationMachineIdentity old:existing)if(old.getStatus()==MachineIdentityStatus.ACTIVE){old.setStatus(MachineIdentityStatus.ROTATING);old.setOverlapExpiresAt(now.plus(Duration.ofMinutes(10)));}
  StationMachineIdentity identity=new StationMachineIdentity();identity.setStationId(token.getStationId());identity.setPublicKeyBase64(Base64.getEncoder().encodeToString(key.getEncoded()));identity.setPublicKeyFingerprint(fingerprint);identity.setKeyVersion(version);identity.setStatus(MachineIdentityStatus.ACTIVE);identity.setEnrolledAt(now);identity.setEnrolledBy(token.getCreatedBy());identity=identities.saveAndFlush(identity);token.setStatus(EnrollmentTokenStatus.CONSUMED);token.setConsumedAt(now);tokens.saveAndFlush(token);station.setClientVersion(request.clientVersion());return new EnrollResponse(identity.getId(),identity.getStationId(),version,"Ed25519");}

 @Transactional public ChallengeResponse challenge(ChallengeRequest request){limits.checkMachine(request.identityId(),"challenge");StationMachineIdentity identity=requireValid(request.identityId());byte[] bytes=new byte[32];random.nextBytes(bytes);String nonce=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);StationAuthChallenge challenge=new StationAuthChallenge();challenge.setIdentityId(identity.getId());challenge.setNonceHash(MachineCrypto.hash(nonce));challenge.setExpiresAt(clock.instant().plusSeconds(60));challenge=challenges.saveAndFlush(challenge);return new ChallengeResponse(challenge.getId(),identity.getId(),nonce,challenge.getExpiresAt(),"UTF-8 challengeId:identityId:nonce signed with Ed25519");}

 @Transactional public MachineTokenResponse token(TokenRequest request){limits.checkMachine(request.identityId(),"token");Instant now=clock.instant();StationMachineIdentity identity=requireValid(request.identityId());StationAuthChallenge challenge=challenges.findByIdForUpdate(request.challengeId()).filter(c->c.getIdentityId().equals(identity.getId())).orElseThrow(this::invalidChallenge);
  if(challenge.getConsumedAt()!=null||!challenge.getExpiresAt().isAfter(now)||!MessageDigest.isEqual(MachineCrypto.hash(request.nonce()).getBytes(java.nio.charset.StandardCharsets.UTF_8),challenge.getNonceHash().getBytes(java.nio.charset.StandardCharsets.UTF_8)))throw invalidChallenge();
  String signed=challenge.getId()+":"+identity.getId()+":"+request.nonce();if(!MachineCrypto.verify(MachineCrypto.publicKey(identity.getPublicKeyBase64()),signed,request.signature()))throw invalidChallenge();challenge.setConsumedAt(now);identity.setLastAuthenticatedAt(now);var issued=jwt.issueMachine(identity.getId(),identity.getStationId(),identity.getKeyVersion());return new MachineTokenResponse(issued.value(),issued.expiresAt(),"Bearer");}

 @Transactional public void heartbeat(HeartbeatRequest request){MachinePrincipal machine=machine("heartbeat");Instant now=clock.instant();GamingStationProfile station=stations.findByResourceId(machine.stationId()).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Station not found"));StationHeartbeat heartbeat=heartbeats.findById(machine.stationId()).orElseGet(StationHeartbeat::new);heartbeat.setStationId(machine.stationId());heartbeat.setIdentityId(machine.identityId());heartbeat.setClientVersion(request.clientVersion());heartbeat.setClientStatus(request.status().name());heartbeat.setLastCommandSequence(request.lastCommandSequence());heartbeat.setLastSeenAt(now);heartbeats.save(heartbeat);station.setLastHeartbeatAt(now);station.setClientVersion(request.clientVersion());}

 @Transactional(readOnly=true)public MachineSnapshotResponse snapshot(){MachinePrincipal machine=machine("snapshot");GamingStationProfile station=stations.findByResourceId(machine.stationId()).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Station not found"));GamingSession session=sessions.findByResourceIdAndStatus(machine.stationId(),GamingSessionStatus.ACTIVE).orElse(null);long cursor=heartbeats.findById(machine.stationId()).map(StationHeartbeat::getLastCommandSequence).orElse(0L);return new MachineSnapshotResponse(clock.instant(),machine.stationId(),machine.identityId(),machine.keyVersion(),station.getOperationalStatus().name(),session==null?null:session.getId(),session==null?null:session.getEndsAt(),cursor);}

 @Transactional(readOnly=true)public List<MachineCommandResponse> poll(long afterSequence){MachinePrincipal machine=machine("poll");Instant now=clock.instant();return commands.findByStationIdAndSequenceGreaterThanOrderBySequence(machine.stationId(),Math.max(0,afterSequence)).stream().filter(c->!c.getAvailableAt().isAfter(now)&&c.getExpiresAt().isAfter(now)).limit(100).map(c->new MachineCommandResponse(c.getSequence(),c.getCommandType().name(),c.getPayloadVersion(),c.getPayload(),c.getAvailableAt())).toList();}

 @Transactional public CommandAckResponse acknowledge(long sequence){MachinePrincipal machine=machine("ack");StationCommand command=commands.findByStationIdAndSequence(machine.stationId(),sequence).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Station command not found"));if(command.getAcknowledgedAt()==null){command.setAcknowledgedAt(clock.instant());commands.saveAndFlush(command);}heartbeats.findById(machine.stationId()).ifPresent(heartbeat->{if(sequence>heartbeat.getLastCommandSequence())heartbeat.setLastCommandSequence(sequence);});return new CommandAckResponse(sequence,command.getAcknowledgedAt());}

 @Transactional(readOnly=true)public SessionLoginResponse sessionLogin(SessionLoginRequest request){MachinePrincipal machine=principal.require();limits.checkMachineCustomerLogin(machine.identityId());String hash=MachineCrypto.hash(request.email().trim().toLowerCase(Locale.ROOT));GamingSession session=sessions.findByResourceIdAndStatus(machine.stationId(),GamingSessionStatus.ACTIVE).orElse(null);if(session==null){loginAttempts.write(machine,null,null,hash,StationSessionLoginOutcome.NO_ACTIVE_SESSION);throw invalidCustomerLogin();}User customer=users.findById(session.getCustomerId()).orElse(null);boolean valid=customer!=null&&customer.getRole()==Role.CUSTOMER&&customer.isActive()&&!customer.isDeleted()&&customer.getEmail().equalsIgnoreCase(request.email().trim())&&passwords.matches(request.password(),customer.getPasswordHash());if(!valid){loginAttempts.write(machine,session.getId(),session.getCustomerId(),hash,StationSessionLoginOutcome.INVALID_CREDENTIALS);throw invalidCustomerLogin();}loginAttempts.write(machine,session.getId(),customer.getId(),hash,StationSessionLoginOutcome.SUCCESS);return new SessionLoginResponse(session.getId(),machine.stationId(),customer.getId(),customer.getName(),session.getStartedAt(),session.getEndsAt(),clock.instant());}

 @Transactional(readOnly=true)public void sessionLogout(SessionLogoutRequest request){MachinePrincipal machine=principal.require();GamingSession session=sessions.findByResourceIdAndStatus(machine.stationId(),GamingSessionStatus.ACTIVE).filter(value->value.getId().equals(request.sessionId())).orElseThrow(this::invalidCustomerLogin);loginAttempts.write(machine,session.getId(),session.getCustomerId(),MachineCrypto.hash("logout:"+session.getCustomerId()),StationSessionLoginOutcome.LOGOUT);}

 private MachinePrincipal machine(String operation){MachinePrincipal value=principal.require();limits.checkMachine(value.identityId(),operation);return value;}
 private StationMachineIdentity requireValid(UUID id){StationMachineIdentity value=identities.findByIdForUpdate(id).orElseThrow(this::invalidChallenge);if(!valid(value))throw new ApplicationException(HttpStatus.UNAUTHORIZED,"Machine identity is unavailable");return value;}
 private boolean valid(StationMachineIdentity i){return i.getStatus()==MachineIdentityStatus.ACTIVE||(i.getStatus()==MachineIdentityStatus.ROTATING&&i.getOverlapExpiresAt()!=null&&i.getOverlapExpiresAt().isAfter(clock.instant()));}
 private ApplicationException invalidEnrollment(){return new ApplicationException(HttpStatus.UNAUTHORIZED,"Enrollment token is invalid or expired");}private ApplicationException invalidChallenge(){return new ApplicationException(HttpStatus.UNAUTHORIZED,"Machine challenge is invalid or expired");}
 private ApplicationException invalidCustomerLogin(){return new ApplicationException(HttpStatus.UNAUTHORIZED,"Customer credentials or active station session are invalid");}
}
