package com.game_manager.gm.machine;
import com.game_manager.gm.audit.*;import com.game_manager.gm.common.error.ApplicationException;import com.game_manager.gm.common.security.*;import com.game_manager.gm.machine.dto.MachineDtos.*;import com.game_manager.gm.station.*;import java.security.SecureRandom;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class MachineIdentityAdminService {
 private final StationEnrollmentTokenRepository tokens;private final StationMachineIdentityRepository identities;private final GamingStationProfileRepository stations;private final CurrentUserProvider current;private final AuditWriter audit;private final Clock clock;private final SecureRandom random=new SecureRandom();
 public MachineIdentityAdminService(StationEnrollmentTokenRepository t,StationMachineIdentityRepository i,GamingStationProfileRepository s,CurrentUserProvider c,AuditWriter a,Clock clock){tokens=t;identities=i;stations=s;current=c;audit=a;this.clock=clock;}
 @Transactional @PreAuthorize("hasAuthority('MACHINE_IDENTITY_MANAGE')")
 public EnrollmentTokenResponse createToken(UUID stationId,EnrollmentPurpose purpose){GamingStationProfile station=stations.findByResourceId(stationId).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Gaming station not found"));if(!station.isClientEnabled())throw new ApplicationException(HttpStatus.CONFLICT,"Gaming Client must be enabled before enrollment");
  boolean hasIdentity=identities.findByStationIdAndStatusIn(stationId,List.of(MachineIdentityStatus.ACTIVE,MachineIdentityStatus.ROTATING)).stream().anyMatch(this::valid);
  if(purpose==EnrollmentPurpose.INITIAL&&hasIdentity)throw new ApplicationException(HttpStatus.CONFLICT,"Station already has a machine identity");
  if(purpose==EnrollmentPurpose.ROTATION&&!hasIdentity)throw new ApplicationException(HttpStatus.CONFLICT,"Station has no active identity to rotate");
  Instant now=clock.instant();tokens.findByStationIdAndStatus(stationId,EnrollmentTokenStatus.ACTIVE).forEach(t->{t.setStatus(EnrollmentTokenStatus.REVOKED);});
  byte[] bytes=new byte[32];random.nextBytes(bytes);String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);StationEnrollmentToken token=new StationEnrollmentToken();token.setStationId(stationId);token.setTokenHash(MachineCrypto.hash(raw));token.setPurpose(purpose);token.setStatus(EnrollmentTokenStatus.ACTIVE);token.setExpiresAt(now.plus(Duration.ofMinutes(10)));token.setCreatedBy(current.requireCurrentUser().id());token=tokens.saveAndFlush(token);
  audit.write("MACHINE_ENROLLMENT_TOKEN_CREATED","PHYSICAL_RESOURCE",stationId,null,Map.of("purpose",purpose.name(),"expiresAt",token.getExpiresAt()),null,AuditVisibility.MANAGEMENT);return new EnrollmentTokenResponse(token.getId(),stationId,purpose,raw,token.getExpiresAt());}
 @Transactional(readOnly=true)@PreAuthorize("hasAuthority('MACHINE_IDENTITY_MANAGE')") public List<MachineIdentityView> identities(UUID stationId){requireStation(stationId);return identities.findByStationIdOrderByKeyVersionDesc(stationId).stream().map(MachineIdentityAdminService::view).toList();}
 @Transactional @PreAuthorize("hasAuthority('MACHINE_IDENTITY_MANAGE')") public void revoke(UUID stationId){requireStation(stationId);Instant now=clock.instant();int count=0;for(StationMachineIdentity i:identities.findByStationIdAndStatusIn(stationId,List.of(MachineIdentityStatus.ACTIVE,MachineIdentityStatus.ROTATING))){i.setStatus(MachineIdentityStatus.REVOKED);i.setRevokedAt(now);count++;}tokens.findByStationIdAndStatus(stationId,EnrollmentTokenStatus.ACTIVE).forEach(t->t.setStatus(EnrollmentTokenStatus.REVOKED));audit.write("MACHINE_IDENTITIES_REVOKED","PHYSICAL_RESOURCE",stationId,null,Map.of("revokedCount",count),"Administrative revocation",AuditVisibility.MANAGEMENT);}
 private boolean valid(StationMachineIdentity i){return i.getStatus()==MachineIdentityStatus.ACTIVE||(i.getStatus()==MachineIdentityStatus.ROTATING&&i.getOverlapExpiresAt()!=null&&i.getOverlapExpiresAt().isAfter(clock.instant()));}
 private GamingStationProfile requireStation(UUID id){return stations.findByResourceId(id).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Gaming station not found"));}
 public static MachineIdentityView view(StationMachineIdentity i){return new MachineIdentityView(i.getId(),i.getStationId(),i.getKeyVersion(),i.getStatus(),i.getPublicKeyFingerprint(),i.getEnrolledAt(),i.getOverlapExpiresAt(),i.getRevokedAt(),i.getLastAuthenticatedAt());}
}
