package com.game_manager.gm.machine;import com.game_manager.gm.common.error.ApplicationException;import com.game_manager.gm.gamingsession.*;import com.game_manager.gm.gamingsession.command.*;import java.time.*;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service@RequiredArgsConstructor public class StationEnforcementProjectionService {private final StationClientEnforcementRepository states;private final StationReconciliationAuditRepository audits;private final Clock clock;
 @Transactional(propagation=Propagation.MANDATORY)public void commandIssued(GamingSession session,StationCommandType type,long sequence){StationClientEnforcement state=state(session.getResourceId());StationEnforcementStatus previous=state.getEnforcementStatus();state.setSessionId(session.getId());state.setLastCommandSequence(Math.max(state.getLastCommandSequence(),sequence));state.setEnforcementStatus(type==StationCommandType.SESSION_TERMINATED||type==StationCommandType.FORCE_LOCK?StationEnforcementStatus.LOCK_PENDING:StationEnforcementStatus.UNLOCKED);state.setReason(type.name());states.save(state);audit(state,session.getId(),null,"COMMAND_ISSUED",previous,sequence,type.name());}
 @Transactional public void leaseIssued(MachinePrincipal machine,UUID leaseId,UUID sessionId,Instant expiresAt,long configVersion,long cursor){StationClientEnforcement state=state(machine.stationId());state.setIdentityId(machine.identityId());state.setSessionId(sessionId);state.setLastLeaseId(leaseId);state.setLastLeaseExpiresAt(expiresAt);state.setLastConfigVersion(Math.max(state.getLastConfigVersion(),configVersion));state.setLastCommandSequence(Math.max(state.getLastCommandSequence(),cursor));state.setClientReportedAt(clock.instant());states.save(state);}
 @Transactional public void heartbeat(MachinePrincipal machine,StationEnforcementStatus reported,UUID sessionId,UUID leaseId,long configVersion,long cursor){StationClientEnforcement state=state(machine.stationId());state.setIdentityId(machine.identityId());state.setClientReportedAt(clock.instant());state.setLastCommandSequence(Math.max(state.getLastCommandSequence(),cursor));state.setLastConfigVersion(Math.max(state.getLastConfigVersion(),configVersion));if(leaseId!=null)state.setLastLeaseId(leaseId);if(sessionId!=null)state.setSessionId(sessionId);if(reported!=null&&reported!=StationEnforcementStatus.LOCKED)state.setEnforcementStatus(reported);states.save(state);}
 @Transactional public Instant lockAck(MachinePrincipal machine,UUID sessionId,long sequence,UUID leaseId,String reason){StationClientEnforcement state=state(machine.stationId());if(state.getSessionId()!=null&&!state.getSessionId().equals(sessionId))throw new ApplicationException(HttpStatus.CONFLICT,"Lock acknowledgement does not match enforcement projection");StationEnforcementStatus previous=state.getEnforcementStatus();Instant now=clock.instant();state.setIdentityId(machine.identityId());state.setSessionId(sessionId);state.setLastCommandSequence(Math.max(state.getLastCommandSequence(),sequence));if(leaseId!=null)state.setLastLeaseId(leaseId);state.setEnforcementStatus(StationEnforcementStatus.LOCKED);state.setLastLockAckAt(now);state.setClientReportedAt(now);state.setReason(reason);states.save(state);audit(state,sessionId,null,"LOCK_ACK",previous,sequence,reason);return now;}
 @Transactional public void operatorRecovery(UUID stationId,UUID sessionId,UUID actorId,String action,long sequence,String details){StationClientEnforcement state=state(stationId);StationEnforcementStatus previous=state.getEnforcementStatus();state.setSessionId(sessionId);state.setLastCommandSequence(Math.max(state.getLastCommandSequence(),sequence));state.setEnforcementStatus(action.equals("OPERATOR_RECOVERY")?StationEnforcementStatus.LOCKED:StationEnforcementStatus.LOCK_PENDING);state.setReason(details);if(action.equals("OPERATOR_RECOVERY"))state.setLastLockAckAt(clock.instant());states.save(state);audit(state,sessionId,actorId,action,previous,sequence,details);}
 @Transactional(readOnly=true)public boolean safeForNewSession(UUID stationId){return states.findById(stationId).map(value->value.getEnforcementStatus()==StationEnforcementStatus.LOCKED||value.getEnforcementStatus()==StationEnforcementStatus.UNKNOWN).orElse(true);}
 private StationClientEnforcement state(UUID stationId){return states.findById(stationId).orElseGet(()->{StationClientEnforcement value=new StationClientEnforcement();value.setStationId(stationId);return value;});}
 private void audit(StationClientEnforcement state,UUID sessionId,UUID actor,String action,StationEnforcementStatus previous,Long sequence,String details){StationReconciliationAudit event=new StationReconciliationAudit();event.setStationId(state.getStationId());event.setSessionId(sessionId);event.setActorId(actor);event.setAction(action);event.setPreviousStatus(previous==null?null:previous.name());event.setResultingStatus(state.getEnforcementStatus().name());event.setCommandSequence(sequence);event.setDetails(details);event.setOccurredAt(clock.instant());audits.save(event);}
}
