spring.application.name=gmanager

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gmanager
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=false

management.endpoints.web.exposure.include=health