spring.application.name=gmanager

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gmanager
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health

app.jwt.secret=6c6d496b5981114a3fa23f0057a3bbd2
app.jwt.expiration-ms=3600000