import type { AuthUser, Permission, Role } from '../types/auth.types'

const profile: Permission[] = [
  'PROFILE_READ', 'PROFILE_UPDATE', 'CATALOG_READ', 'WORKING_HOURS_READ', 'EMPLOYEE_LIST',
]

export const roleCapabilities: Record<Role, Permission[]> = {
  CUSTOMER: [...profile, 'RESERVATION_CREATE', 'RESERVATION_READ_OWN',
    'RESERVATION_CHANGE_STATUS', 'ORDER_CREATE', 'ORDER_READ_OWN', 'ORDER_CHANGE_STATUS'],
  EMPLOYEE: [...profile, 'RESERVATION_READ_ALL', 'RESERVATION_CHANGE_STATUS',
    'ORDER_READ_ALL', 'ORDER_CHANGE_STATUS', 'DASHBOARD_OPERATIONAL', 'REPORT_READ', 'WORKFLOW_SUBMIT'],
  ADMIN: [...profile, 'USER_LIST', 'USER_CREATE', 'USER_DEACTIVATE', 'CATALOG_MANAGE',
    'USER_DELETE', 'USER_RESTORE', 'CUSTOMER_READ', 'CATALOG_DELETE', 'CATALOG_RESTORE', 'AUDIT_READ',
    'WORKING_HOURS_MANAGE', 'RESERVATION_READ_ALL', 'RESERVATION_CHANGE_STATUS',
    'ORDER_READ_ALL', 'ORDER_CHANGE_STATUS', 'DASHBOARD_SUMMARY',
    'DASHBOARD_OPERATIONAL', 'METRICS_READ', 'REPORT_READ', 'REPORT_MANAGE', 'WORKFLOW_ACT', 'WORKFLOW_MANAGE', 'FEATURE_FLAG_MANAGE'],
  OWNER: [...profile, 'USER_LIST', 'USER_CREATE', 'USER_DEACTIVATE', 'CATALOG_MANAGE',
    'USER_DELETE', 'USER_RESTORE', 'CUSTOMER_READ', 'CATALOG_DELETE', 'CATALOG_RESTORE', 'AUDIT_READ',
    'WORKING_HOURS_MANAGE', 'RESERVATION_READ_ALL', 'RESERVATION_CHANGE_STATUS',
    'ORDER_READ_ALL', 'ORDER_CHANGE_STATUS', 'DASHBOARD_SUMMARY',
    'DASHBOARD_OPERATIONAL', 'METRICS_READ', 'REPORT_READ', 'REPORT_MANAGE', 'WORKFLOW_ACT', 'WORKFLOW_MANAGE', 'FEATURE_FLAG_MANAGE'],
}

export function hasCapability(user: AuthUser | null | undefined, permission: Permission): boolean {
  return !!user && (user.permissions ?? roleCapabilities[user.role]).includes(permission)
}
