using GManager.Client.Domain;using GManager.Client.Protocol;
namespace GManager.Client.Service;
public sealed class ClientRuntime(ProtectedIdentityStore store,IMachineProtocolClient protocol,StationPolicyEnforcer policy) {
 readonly SemaphoreSlim gate=new(1,1);public ClientViewState State{get;private set;}=ClientViewState.Locked();public StoredIdentity? Identity{get;private set;}=store.Load();string? token;DateTimeOffset tokenExpiry;
 public void Recover(){var snapshot=store.LoadSnapshot<SessionSnapshot>();if(snapshot is not null)State=State.Apply(snapshot,DateTimeOffset.UtcNow);}
 public async Task Refresh(CancellationToken ct){if(Identity is null)return;await gate.WaitAsync(ct);try{await EnsureToken(ct);await policy.ApplyAsync(await protocol.ConfigurationAsync(token!,ct),Identity.StationId,ct);var snapshot=await protocol.SnapshotAsync(token!,ct);store.SaveSnapshot(snapshot);State=State.Apply(snapshot,DateTimeOffset.UtcNow);}catch(HttpRequestException){State=State.Disconnected();}finally{gate.Release();}}
 public async Task<LocalResponse> Handle(LocalRequest request,CancellationToken ct){if(request.Type=="status")return new(true,null,State,policy.VisibleApplications);if(Identity is null)return new(false,"Stanica nije enrolled.",State);await gate.WaitAsync(ct);try{await EnsureToken(ct);if(request.Type=="login"&&request.Email is not null&&request.Password is not null){var result=await protocol.LoginAsync(token!,request.Email,request.Password,ct);State=State with{EndsAt=result.EndsAt,ServerOffset=result.ServerTime-DateTimeOffset.UtcNow};State=State.Welcome(result.CustomerName);policy.StartAutoApplications();return new(true,null,State,policy.VisibleApplications);}if(request.Type=="launch"&&State.Mode==ClientMode.Active&&request.ApplicationCode is not null){policy.Launch(request.ApplicationCode);return new(true,null,State,policy.VisibleApplications);}if(request.Type=="logout"&&request.SessionId is not null){await protocol.LogoutAsync(token!,request.SessionId.Value,ct);policy.StopCustomerProcesses();State=ClientViewState.Locked("Online");return new(true,null,State);}return new(false,"Nepodržan lokalni zahtev.",State);}catch(HttpRequestException){State=State.Disconnected();return new(false,"Server nije dostupan.",State);}finally{gate.Release();}}
 async Task EnsureToken(CancellationToken ct){if(token is not null&&tokenExpiry>DateTimeOffset.UtcNow.AddMinutes(1))return;using var signer=new Ed25519Signer(Identity!.PrivateKey);var value=await protocol.AuthenticateAsync(Identity.IdentityId,signer,ct);token=value.Token;tokenExpiry=value.ExpiresAt;}
}
