using System.Security.Cryptography;using System.Text.Json;using GManager.Client.Domain;using GManager.Client.Protocol;
namespace GManager.Client.Service;
public sealed class ClientRuntime(ProtectedIdentityStore store,IMachineProtocolClient protocol,StationPolicyEnforcer policy,SessionLeaseVerifier leases,OperationalEventWriter events) {
 readonly SemaphoreSlim gate=new(1,1);public ClientViewState State{get;private set;}=ClientViewState.Locked();public StoredIdentity? Identity{get;private set;}=store.Load();string? token;DateTimeOffset tokenExpiry;ClientRecoveryState? recovery;TrustedLeaseClock trusted=new(DateTimeOffset.UtcNow);
 public void Recover(){try{recovery=store.LoadSnapshot<ClientRecoveryState>();if(recovery is null)return;trusted=new TrustedLeaseClock(recovery.TrustedUtcFloor);ApplyLease(recovery.Lease);events.Write("RECOVERY_APPLIED",State.Mode.ToString());}catch(JsonException){LockLocal("Lokalni snapshot nije validan");events.Write("RECOVERY_REJECTED","LOCKED");}}
 public async Task Refresh(CancellationToken ct){if(Identity is null)return;await gate.WaitAsync(ct);try{await EnsureToken(ct);await policy.ApplyAsync(await protocol.ConfigurationAsync(token!,ct),Identity.StationId,ct);var envelope=await protocol.LeaseAsync(token!,ct);var lease=leases.Verify(envelope,Identity.StationId);if(lease.ConfigurationVersion!=policy.CurrentVersion)throw new CryptographicException("Lease and executable policy versions do not match");long cursor=recovery?.AppliedSequence??0;recovery=new ClientRecoveryState(envelope,lease,cursor,trusted.Now(),recovery?.PendingLockSequence,recovery?.PendingLockSessionId,recovery?.LocallyLocked??true);await ReconcileCommands(ct);ApplyLease(lease);await AckPendingLock(ct);SaveRecovery();await protocol.HeartbeatAsync(token!,Heartbeat(),ct);}catch(HttpRequestException){EnforceCachedLease();}catch(CryptographicException){LockLocal("Potpisani lease nije validan");SaveRecovery();}finally{gate.Release();}}
 public async Task<LocalResponse> Handle(LocalRequest request,CancellationToken ct){if(request.Type=="status")return new(true,null,State,policy.VisibleApplications);if(Identity is null)return new(false,"Stanica nije enrolled.",State);await gate.WaitAsync(ct);try{await EnsureToken(ct);if(request.Type=="login"&&request.Email is not null&&request.Password is not null&&recovery?.Lease.Directive=="ACTIVE"&&trusted.Now()<recovery.Lease.GraceEndsAt){var result=await protocol.LoginAsync(token!,request.Email,request.Password,ct);State=State with{EndsAt=result.EndsAt,ServerOffset=result.ServerTime-DateTimeOffset.UtcNow};State=State.Welcome(result.CustomerName);policy.StartAutoApplications();return new(true,null,State,policy.VisibleApplications);}if(request.Type=="launch"&&State.Mode==ClientMode.Active&&request.ApplicationCode is not null){policy.Launch(request.ApplicationCode);return new(true,null,State,policy.VisibleApplications);}if(request.Type=="logout"&&request.SessionId is not null){await protocol.LogoutAsync(token!,request.SessionId.Value,ct);LockLocal("Customer logout");return new(true,null,State);}return new(false,"Zahtev nije dozvoljen u trenutnom lease stanju.",State);}catch(HttpRequestException){EnforceCachedLease();return new(false,"Server nije dostupan.",State);}finally{gate.Release();}}
 async Task ReconcileCommands(CancellationToken ct){if(recovery is null)return;var commands=await protocol.CommandsAsync(token!,recovery.AppliedSequence,ct);foreach(var command in commands.OrderBy(value=>value.Sequence)){var decision=CommandSequenceReducer.Decide(recovery.AppliedSequence,command.Sequence);if(decision==SequenceDecision.Duplicate)continue;if(decision==SequenceDecision.Gap)break;using var payload=JsonDocument.Parse(command.Payload);Guid sessionId=payload.RootElement.GetProperty("sessionId").GetGuid();if(command.Type is "SESSION_TERMINATED" or "FORCE_LOCK"){LockLocal(command.Type);recovery=recovery with{AppliedSequence=command.Sequence,PendingLockSequence=command.Sequence,PendingLockSessionId=sessionId,LocallyLocked=true};}else if(command.Type is "SESSION_STARTED" or "SESSION_EXTENDED")recovery=recovery with{AppliedSequence=command.Sequence};SaveRecovery();await protocol.AckAsync(token!,command.Sequence,ct);}}
 async Task AckPendingLock(CancellationToken ct){if(recovery?.PendingLockSequence is not long sequence||recovery.PendingLockSessionId is not Guid sessionId||!recovery.LocallyLocked)return;await protocol.LockAckAsync(token!,sessionId,sequence,recovery.Lease.LeaseId,"Client locally locked",ct);recovery=recovery with{PendingLockSequence=null,PendingLockSessionId=null};}
 void ApplyLease(SessionLease lease){var now=trusted.Now();if(LeaseDeadlinePolicy.MustLock(lease,now)){LockLocal(now>=lease.GraceEndsAt?"Lease and offline grace expired":"Backend lock directive");return;}if(State.Mode!=ClientMode.Active||State.SessionId!=lease.SessionId)State=State.Apply(new SessionSnapshot(lease.StationId,lease.SessionId,lease.SessionEndsAt,lease.IssuedAt,lease.CommandCursor,"AVAILABLE"),DateTimeOffset.UtcNow);}
 void EnforceCachedLease(){if(recovery is null){LockLocal("No signed lease");return;}ApplyLease(recovery.Lease);recovery=recovery with{TrustedUtcFloor=trusted.Now(),LocallyLocked=State.Mode==ClientMode.Locked};SaveRecovery();}
 void LockLocal(string reason){policy.StopCustomerProcesses();State=ClientViewState.Locked("Zaključano · "+reason);events.Write("LOCAL_LOCK",reason switch{"FORCE_LOCK"=>"FORCE_LOCK","SESSION_TERMINATED"=>"SESSION_TERMINATED",_=>"SAFETY"});if(recovery is not null)recovery=recovery with{LocallyLocked=true};}
 Heartbeat Heartbeat()=>new("0.1.0-dev",State.Mode==ClientMode.Active?"SESSION_ACTIVE":"LOCKED",recovery?.AppliedSequence??0,State.Mode==ClientMode.Active?"UNLOCKED":"LOCKED",recovery?.Lease.SessionId,recovery?.Lease.LeaseId,policy.CurrentVersion);
 void SaveRecovery(){if(recovery is not null){recovery=recovery with{TrustedUtcFloor=trusted.Now()};store.SaveSnapshot(recovery);}}
 async Task EnsureToken(CancellationToken ct){if(token is not null&&tokenExpiry>DateTimeOffset.UtcNow.AddMinutes(1))return;using var signer=new Ed25519Signer(Identity!.PrivateKey);var value=await protocol.AuthenticateAsync(Identity.IdentityId,signer,ct);token=value.Token;tokenExpiry=value.ExpiresAt;}
}
