using System.Diagnostics;using System.Security.Cryptography;using System.Text.Json;using GManager.Client.Protocol;using NSec.Cryptography;
namespace GManager.Client.Service;
public sealed record ClientRecoveryState(SignedSessionLease Envelope,SessionLease Lease,long AppliedSequence,DateTimeOffset TrustedUtcFloor,long? PendingLockSequence,Guid? PendingLockSessionId,bool LocallyLocked);
public sealed class SessionLeaseVerifier(IConfiguration configuration) {static readonly SignatureAlgorithm Algorithm=SignatureAlgorithm.Ed25519;
 public SessionLease Verify(SignedSessionLease envelope,Guid stationId){if(envelope.Algorithm!="Ed25519"||envelope.KeyId!=configuration["Policy:SigningKeyId"])throw new CryptographicException("Lease signing key is not trusted");byte[] payload=Decode(envelope.Payload),signature=Decode(envelope.Signature);using var key=PublicKey.Import(Algorithm,Convert.FromBase64String(configuration["Policy:SigningPublicKey"]??throw new InvalidOperationException("Lease verification key is not configured")),KeyBlobFormat.PkixPublicKey);if(!Algorithm.Verify(key,payload,signature))throw new CryptographicException("Session lease signature is invalid");var lease=JsonSerializer.Deserialize<SessionLease>(payload,new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new InvalidDataException("Session lease is invalid");if(lease.StationId!=stationId)throw new CryptographicException("Session lease belongs to another station");if(lease.GraceEndsAt<lease.ExpiresAt||lease.SessionEndsAt is not null&&lease.GraceEndsAt>lease.SessionEndsAt)throw new CryptographicException("Session lease grants an invalid grace interval");return lease;}
 static byte[] Decode(string value){var padded=value.Replace('-','+').Replace('_','/');padded+=new string('=',(4-padded.Length%4)%4);return Convert.FromBase64String(padded);}}
public sealed class TrustedLeaseClock {readonly Stopwatch monotonic=Stopwatch.StartNew();readonly DateTimeOffset anchor=DateTimeOffset.UtcNow;DateTimeOffset floor;public TrustedLeaseClock(DateTimeOffset floor){this.floor=floor;}public DateTimeOffset Now(){var value=anchor+monotonic.Elapsed;if(value<floor)value=floor;else floor=value;return value;}public DateTimeOffset Floor=>floor;}
public enum SequenceDecision { Duplicate,Apply,Gap }
public static class CommandSequenceReducer {public static SequenceDecision Decide(long applied,long incoming)=>incoming<=applied?SequenceDecision.Duplicate:incoming==applied+1?SequenceDecision.Apply:SequenceDecision.Gap;}
public static class LeaseDeadlinePolicy {public static bool MustLock(SessionLease lease,DateTimeOffset trustedNow)=>lease.Directive!="ACTIVE"||lease.SessionId is null||trustedNow>=lease.GraceEndsAt||lease.SessionEndsAt is not null&&trustedNow>=lease.SessionEndsAt;}
