using System.Diagnostics;using System.Management;using System.Security.Cryptography;using System.Security.Cryptography.X509Certificates;using System.Text;using System.Text.Json;using System.Xml.Linq;using GManager.Client.Domain;using GManager.Client.Protocol;using NSec.Cryptography;
#pragma warning disable SYSLIB0026
namespace GManager.Client.Service;
public sealed class StationPolicyEnforcer(IConfiguration configuration,ProtectedIdentityStore store,ILogger<StationPolicyEnforcer> logger) {
 static readonly SignatureAlgorithm Signature=SignatureAlgorithm.Ed25519;readonly Dictionary<string,PolicyApplication> allowed=new(StringComparer.OrdinalIgnoreCase);readonly HashSet<int> roots=[];long version;
 public IReadOnlyList<ClientApplication> VisibleApplications=>allowed.Values.Where(x=>x.Type is "GAME" or "LAUNCHER").OrderBy(x=>x.LaunchOrder).Select(x=>new ClientApplication(x.Code,x.Name,x.Type)).ToList();
 public async Task ApplyAsync(SignedStationPolicy signed,Guid stationId,CancellationToken ct){byte[] payload=Decode(signed.Payload),signature=Decode(signed.Signature);var keyId=configuration["Policy:SigningKeyId"]??throw new InvalidOperationException("Policy signing key id is not configured");if(signed.Algorithm!="Ed25519"||signed.KeyId!=keyId)throw new CryptographicException("Station policy signing key is not trusted");using var key=PublicKey.Import(Signature,Convert.FromBase64String(configuration["Policy:SigningPublicKey"]??throw new InvalidOperationException("Policy public key is not configured")),KeyBlobFormat.PkixPublicKey);if(!Signature.Verify(key,payload,signature))throw new CryptographicException("Station policy signature is invalid");var policy=JsonSerializer.Deserialize<StationPolicy>(payload,new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new InvalidDataException("Station policy payload is invalid");if(policy.StationId!=stationId)throw new CryptographicException("Station policy belongs to another station");if(policy.ConfigurationVersion<version)throw new CryptographicException("Station policy downgrade is forbidden");if(policy.ConfigurationVersion==version)return;foreach(var app in policy.Applications)Validate(app);var previous=store.LoadPolicy<StationPolicy>();try{await ApplyOsPolicy(policy,ct);store.SavePolicy(policy);allowed.Clear();foreach(var app in policy.Applications)allowed.Add(app.Code,app);version=policy.ConfigurationVersion;}catch{if(previous is not null)await ApplyOsPolicy(previous,ct);throw;}}
 public void Launch(string code){if(!allowed.TryGetValue(code,out var app)||app.Type=="HELPER")throw new UnauthorizedAccessException("Executable is not launchable from Shell");Start(app);}
 public void StartAutoApplications(){foreach(var app in allowed.Values.Where(value=>value.AutoStart).OrderBy(value=>value.LaunchOrder))Start(app);}
 void Start(PolicyApplication app){Validate(app);if(Process.GetProcessesByName(Path.GetFileNameWithoutExtension(app.ExecutablePath)).Any())return;var start=new ProcessStartInfo(app.ExecutablePath){UseShellExecute=false,WorkingDirectory=Path.GetDirectoryName(app.ExecutablePath)!};if(!string.IsNullOrWhiteSpace(app.Arguments))foreach(var value in CommandLine.Split(app.Arguments))start.ArgumentList.Add(value);var process=Process.Start(start)??throw new InvalidOperationException("Configured application could not be started");lock(roots)roots.Add(process.Id);_ = GuardTree(process.Id);}
 public void StopCustomerProcesses(){lock(roots){foreach(var id in roots)try{Process.GetProcessById(id).Kill(true);}catch(ArgumentException){}roots.Clear();}}
 void Validate(PolicyApplication app){if(!Path.IsPathFullyQualified(app.ExecutablePath)||!app.ExecutablePath.EndsWith(".exe",StringComparison.OrdinalIgnoreCase)||app.ExecutablePath.IndexOfAny(['*','?'])>=0)throw new InvalidDataException("Policy contains an invalid executable path");if(!File.Exists(app.ExecutablePath))throw new FileNotFoundException("Configured executable is unavailable",app.ExecutablePath);if(app.ExecutableSha256 is not null){using var stream=File.OpenRead(app.ExecutablePath);if(!Convert.ToHexString(SHA256.HashData(stream)).Equals(app.ExecutableSha256,StringComparison.OrdinalIgnoreCase))throw new CryptographicException("Executable hash does not match station policy");}if(app.PublisherCertificateThumbprint is not null||app.Publisher is not null){using var certificate=new X509Certificate2(X509Certificate.CreateFromSignedFile(app.ExecutablePath));if(app.PublisherCertificateThumbprint is not null&&!certificate.Thumbprint.Equals(app.PublisherCertificateThumbprint,StringComparison.OrdinalIgnoreCase))throw new CryptographicException("Executable signer certificate does not match station policy");if(app.Publisher is not null&&!certificate.Subject.Contains(app.Publisher,StringComparison.OrdinalIgnoreCase))throw new CryptographicException("Executable publisher does not match station policy");}if(app.ExecutableSha256 is null&&app.PublisherCertificateThumbprint is null&&app.Publisher is null)throw new CryptographicException("Executable has no trust constraint");if(app.MinimumFileVersion is not null&&Version.Parse(FileVersionInfo.GetVersionInfo(app.ExecutablePath).FileVersion??"0.0")<Version.Parse(app.MinimumFileVersion))throw new CryptographicException("Executable version is below station policy minimum");}
 async Task ApplyOsPolicy(StationPolicy policy,CancellationToken ct){var root=Path.GetDirectoryName(store.SnapshotPath)!;Directory.CreateDirectory(root);var path=Path.Combine(root,$"applocker-{policy.ConfigurationVersion}.xml");await File.WriteAllTextAsync(path,AppLockerXml.Create(policy),ct);var script=Path.Combine(AppContext.BaseDirectory,"apply-policy.ps1");var info=new ProcessStartInfo("powershell.exe"){UseShellExecute=false,CreateNoWindow=true};foreach(var arg in new[]{"-NoProfile","-NonInteractive","-ExecutionPolicy","AllSigned","-File",script,"-PolicyPath",path,"-RollbackDirectory",root})info.ArgumentList.Add(arg);var process=Process.Start(info)??throw new InvalidOperationException("AppLocker policy process could not start");await process.WaitForExitAsync(ct);if(process.ExitCode!=0)throw new InvalidOperationException("AppLocker policy update failed; previous policy was restored");}
 async Task GuardTree(int root){while(true){await Task.Delay(1000);try{using var query=new ManagementObjectSearcher("SELECT ProcessId,ParentProcessId,ExecutablePath FROM Win32_Process");foreach(ManagementObject item in query.Get()){var parent=Convert.ToInt32((uint)item["ParentProcessId"]);lock(roots)if(parent!=root&&!roots.Contains(parent))continue;var id=Convert.ToInt32((uint)item["ProcessId"]);var path=item["ExecutablePath"] as string;if(path is not null&&!allowed.Values.Any(x=>x.ExecutablePath.Equals(path,StringComparison.OrdinalIgnoreCase))){logger.LogWarning("Terminating executable outside signed station policy");try{Process.GetProcessById(id).Kill(true);}catch(ArgumentException){}}else lock(roots)roots.Add(id);}if(!Process.GetProcesses().Any(x=>x.Id==root))return;}catch(ManagementException){return;}}}
 static byte[] Decode(string value){string padded=value.Replace('-','+').Replace('_','/');padded+=new string('=',(4-padded.Length%4)%4);return Convert.FromBase64String(padded);}
}
static class CommandLine {public static IEnumerable<string> Split(string value){var current=new StringBuilder();bool quoted=false;foreach(char c in value){if(c=='\"'){quoted=!quoted;continue;}if(char.IsWhiteSpace(c)&&!quoted){if(current.Length>0){yield return current.ToString();current.Clear();}}else current.Append(c);}if(quoted)throw new InvalidDataException("Unbalanced command line quotes");if(current.Length>0)yield return current.ToString();}}
public static class AppLockerXml {public static string Create(StationPolicy policy){XNamespace ns="http://schemas.microsoft.com/windows/2010/12/applicationcontrolpolicy";var rules=policy.Applications.Select(app=>new XElement(ns+"FilePathRule",new XAttribute("Id",Guid.NewGuid()),new XAttribute("Name",app.Code),new XAttribute("Description",$"G-Manager config {policy.ConfigurationVersion}"),new XAttribute("UserOrGroupSid","S-1-5-32-545"),new XAttribute("Action","Allow"),new XElement(ns+"Conditions",new XElement(ns+"FilePathCondition",new XAttribute("Path",app.ExecutablePath)))));return new XDocument(new XElement(ns+"AppLockerPolicy",new XAttribute("Version","1"),new XElement(ns+"RuleCollection",new XAttribute("Type","Exe"),new XAttribute("EnforcementMode","Enabled"),rules),new XElement(ns+"RuleCollection",new XAttribute("Type","Script"),new XAttribute("EnforcementMode","Enabled")),new XElement(ns+"RuleCollection",new XAttribute("Type","Msi"),new XAttribute("EnforcementMode","Enabled")))).ToString(SaveOptions.DisableFormatting);}}
