using System.IO.Pipes;using System.Text.Json;using System.Windows;using System.Windows.Threading;using GManager.Client.Domain;
namespace GManager.Client.Shell;
public partial class MainWindow:Window {readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromSeconds(1)};Guid? sessionId;IReadOnlyList<ClientApplication> apps=[];
 public MainWindow(){InitializeComponent();timer.Tick+=async(_,_)=>await RefreshStatus();timer.Start();Loaded+=async(_,_)=>await RefreshStatus();}
 async Task<LocalResponse> Send(LocalRequest request){await using var pipe=new NamedPipeClientStream(".","GManager.Client",PipeDirection.InOut,PipeOptions.Asynchronous);await pipe.ConnectAsync(2000);await JsonSerializer.SerializeAsync(pipe,request);await pipe.FlushAsync();return (await JsonSerializer.DeserializeAsync<LocalResponse>(pipe))!;}
 async Task RefreshStatus(){try{var response=await Send(new("status",Guid.NewGuid().ToString("N")));apps=response.Applications??[];Render(response.State);}catch{Connectivity.Text="Service nije dostupan";}}
 async void Login_Click(object sender,RoutedEventArgs e){try{var response=await Send(new("login",Guid.NewGuid().ToString("N"),Email.Text,Password.Password));Password.Clear();Error.Text=response.Error??"";Render(response.State);}catch{Error.Text="G-Manager Service nije dostupan.";}}
 async void Logout_Click(object sender,RoutedEventArgs e){if(sessionId is null)return;var response=await Send(new("logout",Guid.NewGuid().ToString("N"),SessionId:sessionId));Render(response.State);}
 async void Launch_Click(object sender,RoutedEventArgs e){if(sender is not System.Windows.Controls.Button button||button.Tag is not string code)return;var response=await Send(new("launch",Guid.NewGuid().ToString("N"),ApplicationCode:code));Error.Text=response.Error??"";}
 void Render(ClientViewState value){sessionId=value.SessionId;Heading.Text=value.Heading;Connectivity.Text=value.Connectivity;var remaining=value.Remaining(DateTimeOffset.UtcNow);Countdown.Text=value.EndsAt is null?"":$"{Math.Max(0,(int)remaining.TotalHours):00}:{Math.Max(0,remaining.Minutes):00}:{Math.Max(0,remaining.Seconds):00}";var active=value.Mode==ClientMode.Active;Email.Visibility=Password.Visibility=Login.Visibility=active?Visibility.Collapsed:Visibility.Visible;Logout.Visibility=active?Visibility.Visible:Visibility.Collapsed;Applications.Children.Clear();if(active)foreach(var app in apps){var button=new System.Windows.Controls.Button{Content=$"{app.Name} ({app.Type})",Tag=app.Code,Height=42,Margin=new Thickness(0,4,0,4)};button.Click+=Launch_Click;Applications.Children.Add(button);}}
}
