package com.game_manager.gm.notification;
import com.game_manager.gm.common.config.GManagerProperties; import com.game_manager.gm.common.observability.SensitiveDataSanitizer; import com.game_manager.gm.user.UserService;
import io.micrometer.core.instrument.MeterRegistry; import java.time.Clock; import java.util.List; import org.springframework.data.domain.PageRequest; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;
@Component public class NotificationDeliveryWorker {
 private final NotificationDeliveryRepository repository;private final EmailDeliveryAdapter email;private final UserService users;private final Clock clock;private final MeterRegistry metrics;private final GManagerProperties.Notifications config;
 public NotificationDeliveryWorker(NotificationDeliveryRepository repository,EmailDeliveryAdapter email,UserService users,Clock clock,MeterRegistry metrics,GManagerProperties properties){this.repository=repository;this.email=email;this.users=users;this.clock=clock;this.metrics=metrics;this.config=properties.notifications();}
 @Scheduled(fixedDelayString="${app.notifications.delivery-poll-interval-millis:2000}") @Transactional public void deliver(){if(!config.emailEnabled())return;List<NotificationDeliveryAttempt> batch=repository.findByStatusAndAvailableAtLessThanEqualOrderByCreatedAt(DeliveryStatus.PENDING,clock.instant(),PageRequest.of(0,config.deliveryBatchSize()));batch.forEach(this::attempt);}
 private void attempt(NotificationDeliveryAttempt delivery){delivery.setStatus(DeliveryStatus.PROCESSING);delivery.setAttempts(delivery.getAttempts()+1);try{Notification n=delivery.getNotification();String address=users.activeEmail(n.getRecipientId()).orElseThrow(()->new IllegalStateException("Recipient is inactive"));email.deliver(address,n.getTitle(),n.getBody());delivery.setStatus(DeliveryStatus.DELIVERED);delivery.setDeliveredAt(clock.instant());delivery.setLastError(null);metrics.counter("gm.notification.delivered","channel","email").increment();}catch(RuntimeException error){boolean dead=delivery.getAttempts()>=config.maxDeliveryAttempts();delivery.setStatus(dead?DeliveryStatus.DEAD:DeliveryStatus.PENDING);delivery.setAvailableAt(clock.instant().plusSeconds(backoff(delivery.getAttempts())));String safe=SensitiveDataSanitizer.redact(error.getMessage()==null?"Delivery failed":error.getMessage());delivery.setLastError(safe.substring(0,Math.min(500,safe.length())));metrics.counter("gm.notification.failed","channel","email","outcome",dead?"dead":"retry").increment();}}
 private long backoff(int attempt){return config.initialBackoffSeconds()*(1L<<Math.min(Math.max(0,attempt-1),20));}
}
