package com.game_manager.gm.customer.crm;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.game_manager.gm.common.security.Role;import com.game_manager.gm.user.*;import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.*;import testsupport.DatabaseCleaner;import tools.jackson.databind.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class CustomerCrmIntegrationTest {@Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired PasswordEncoder encoder;@Autowired JdbcTemplate jdbc;@Autowired CustomerCrmService service;private final ObjectMapper mapper=new ObjectMapper();@BeforeEach void clean(){DatabaseCleaner.clean(jdbc);}
 @Test void crmIsManagementOnlyAuditedSearchableAndOptimisticallyUpdated()throws Exception{User owner=user(Role.OWNER),customer=user(Role.CUSTOMER),outsider=user(Role.CUSTOMER);String ownerToken=login(owner),outsiderToken=login(outsider);
  mvc.perform(post("/api/v1/customers/{id}/crm/notes",customer.getId()).header("Authorization",bearer(outsiderToken)).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"Ne sme\"}")).andExpect(status().isForbidden());
  JsonNode note=node(mvc.perform(post("/api/v1/customers/{id}/crm/notes",customer.getId()).header("Authorization",bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"Preferira jutarnje termine\"}")).andExpect(status().isCreated()).andReturn());
  JsonNode tagged=node(mvc.perform(post("/api/v1/customers/{id}/crm/tags",customer.getId()).header("Authorization",bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"VIP\"}")).andExpect(status().isOk()).andReturn());
  mvc.perform(get("/api/v1/customers/{id}/crm",customer.getId()).header("Authorization",bearer(ownerToken)).param("search","vip")).andExpect(status().isOk()).andExpect(jsonPath("$.tags[0]").value("VIP")).andExpect(jsonPath("$.notes").isEmpty());
  mvc.perform(put("/api/v1/customers/{id}/crm/notes/{noteId}",customer.getId(),note.get("id").asText()).header("Authorization",bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"Ažurirano\",\"version\":99}")).andExpect(status().isConflict());
  mvc.perform(put("/api/v1/customers/{id}/crm/notes/{noteId}",customer.getId(),note.get("id").asText()).header("Authorization",bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"Ažurirano\",\"version\":"+note.get("version").asLong()+"}")).andExpect(status().isOk());
  mvc.perform(delete("/api/v1/customers/{id}/crm/tags/{tag}",customer.getId(),"VIP").header("Authorization",bearer(ownerToken)).param("version","99")).andExpect(status().isConflict());
  mvc.perform(delete("/api/v1/customers/{id}/crm/tags/{tag}",customer.getId(),"VIP").header("Authorization",bearer(ownerToken)).param("version",tagged.get("version").asText())).andExpect(status().isOk()).andExpect(jsonPath("$.tags").isEmpty());
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_events WHERE resource_type IN ('CUSTOMER_CRM_NOTE','CUSTOMER_CRM_PROFILE')",Integer.class)).isEqualTo(4);assertThat(users.findById(customer.getId()).orElseThrow().getName()).isEqualTo("CUSTOMER");
 }
 @Test void expiredNotesArePurgedByRetentionWithoutAffectingCustomerIdentity()throws Exception{User owner=user(Role.OWNER),customer=user(Role.CUSTOMER);String token=login(owner);JsonNode note=node(mvc.perform(post("/api/v1/customers/{id}/crm/notes",customer.getId()).header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"Privremena beleška\"}")).andExpect(status().isCreated()).andReturn());jdbc.update("UPDATE customer_crm_notes SET expires_at=DATEADD('DAY',-1,CURRENT_TIMESTAMP) WHERE id=?",note.get("id").asText());assertThat(service.purgeExpired()).isEqualTo(1);mvc.perform(get("/api/v1/customers/{id}/crm",customer.getId()).header("Authorization",bearer(token))).andExpect(status().isOk()).andExpect(jsonPath("$.notes").isEmpty());assertThat(users.existsById(customer.getId())).isTrue();}
 private User user(Role role){return users.saveAndFlush(new User(role.name(),role+"-crm-"+UUID.randomUUID()+"@example.test",encoder.encode("StrongPass1!"),role,true,null));}private String login(User user)throws Exception{return node(mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+user.getEmail()+"\",\"password\":\"StrongPass1!\"}")).andExpect(status().isOk()).andReturn()).get("token").asText();}private JsonNode node(MvcResult result){return mapper.readTree(result.getResponse().getContentAsByteArray());}private String bearer(String token){return "Bearer "+token;}}
