package com.game_manager.gm.customer.crm;
import com.game_manager.gm.audit.*;import com.game_manager.gm.common.error.ApplicationException;import com.game_manager.gm.common.security.CurrentUserProvider;import com.game_manager.gm.customer.crm.dto.*;import com.game_manager.gm.user.UserService;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.PageRequest;import org.springframework.http.HttpStatus;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor
public class CustomerCrmService {private static final long RETENTION_DAYS=730;private final CustomerCrmProfileRepository profiles;private final CustomerCrmNoteRepository notes;private final CustomerCrmTagRepository tags;private final UserService users;private final CurrentUserProvider currentUser;private final AuditWriter audit;private final Clock clock;
 @Transactional(readOnly=true) @PreAuthorize("hasAuthority('CUSTOMER_READ')") public CustomerCrmResponse get(UUID customerId,String search){users.customerReference(customerId);CustomerCrmProfile profile=profiles.findByCustomerId(customerId).orElse(null);if(profile==null)return new CustomerCrmResponse(customerId,0L,List.of(),List.of());String term=normalizeSearch(search);List<CrmNoteResponse> found=notes.search(profile.getId(),term,PageRequest.of(0,100)).stream().map(CrmNoteResponse::from).toList();List<String> values=profile.getTags().stream().map(CustomerCrmTag::getName).filter(name->term==null||name.toLowerCase(Locale.ROOT).contains(term.toLowerCase(Locale.ROOT))).sorted(String.CASE_INSENSITIVE_ORDER).toList();return new CustomerCrmResponse(customerId,profile.getVersion(),found,values);}
 @Transactional @PreAuthorize("hasAuthority('CUSTOMER_CRM_MANAGE')") public CrmNoteResponse addNote(UUID customerId,CrmNoteRequest request){CustomerCrmProfile profile=requireProfile(customerId);CustomerCrmNote note=new CustomerCrmNote();note.setProfile(profile);note.setBody(request.body().trim());note.setCreatedBy(currentUser.requireCurrentUser().id());note.setExpiresAt(clock.instant().plus(RETENTION_DAYS,ChronoUnit.DAYS));note=notes.saveAndFlush(note);audit.write("CUSTOMER_CRM_NOTE_CREATED","CUSTOMER_CRM_NOTE",note.getId(),null,Map.of("customerId",customerId,"body",note.getBody()),null,AuditVisibility.MANAGEMENT);return CrmNoteResponse.from(note);}
 @Transactional @PreAuthorize("hasAuthority('CUSTOMER_CRM_MANAGE')") public CrmNoteResponse updateNote(UUID customerId,UUID noteId,CrmNoteRequest request){CustomerCrmNote note=requireNote(customerId,noteId);requireVersion(note.getVersion(),request.version());String before=note.getBody();note.setBody(request.body().trim());note=notes.saveAndFlush(note);audit.write("CUSTOMER_CRM_NOTE_UPDATED","CUSTOMER_CRM_NOTE",noteId,Map.of("body",before),Map.of("body",note.getBody()),null,AuditVisibility.MANAGEMENT);return CrmNoteResponse.from(note);}
 @Transactional @PreAuthorize("hasAuthority('CUSTOMER_CRM_MANAGE')") public void deleteNote(UUID customerId,UUID noteId,long version){CustomerCrmNote note=requireNote(customerId,noteId);requireVersion(note.getVersion(),version);notes.delete(note);audit.write("CUSTOMER_CRM_NOTE_DELETED","CUSTOMER_CRM_NOTE",noteId,Map.of("customerId",customerId,"body",note.getBody()),null,null,AuditVisibility.MANAGEMENT);}
 @Transactional @PreAuthorize("hasAuthority('CUSTOMER_CRM_MANAGE')") public CustomerCrmResponse addTag(UUID customerId,CrmTagRequest request){CustomerCrmProfile profile=requireProfile(customerId);String name=request.name().trim(),normalized=name.toLowerCase(Locale.ROOT);CustomerCrmTag tag=tags.findByNormalizedName(normalized).orElseGet(()->{CustomerCrmTag value=new CustomerCrmTag();value.setName(name);value.setNormalizedName(normalized);return tags.save(value);});if(profile.getTags().add(tag)){profiles.saveAndFlush(profile);audit.write("CUSTOMER_CRM_TAG_ADDED","CUSTOMER_CRM_PROFILE",profile.getId(),null,Map.of("customerId",customerId,"tag",name),null,AuditVisibility.MANAGEMENT);}return getInternal(customerId);}
 @Transactional @PreAuthorize("hasAuthority('CUSTOMER_CRM_MANAGE')") public CustomerCrmResponse removeTag(UUID customerId,String name,long version){CustomerCrmProfile profile=profiles.findByCustomerId(customerId).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"Customer CRM profile not found"));requireVersion(profile.getVersion(),version);String normalized=name.trim().toLowerCase(Locale.ROOT);CustomerCrmTag tag=tags.findByNormalizedName(normalized).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"CRM tag not found"));if(profile.getTags().remove(tag)){profiles.saveAndFlush(profile);audit.write("CUSTOMER_CRM_TAG_REMOVED","CUSTOMER_CRM_PROFILE",profile.getId(),Map.of("tag",tag.getName()),null,null,AuditVisibility.MANAGEMENT);}return getInternal(customerId);}
 @Scheduled(cron="0 30 3 * * *") @Transactional public long purgeExpired(){return notes.deleteByExpiresAtBefore(clock.instant());}
 private CustomerCrmResponse getInternal(UUID customerId){CustomerCrmProfile profile=profiles.findByCustomerId(customerId).orElseThrow();return new CustomerCrmResponse(customerId,profile.getVersion(),notes.search(profile.getId(),null,PageRequest.of(0,100)).stream().map(CrmNoteResponse::from).toList(),profile.getTags().stream().map(CustomerCrmTag::getName).sorted(String.CASE_INSENSITIVE_ORDER).toList());}
 private CustomerCrmProfile requireProfile(UUID customerId){users.customerReference(customerId);return profiles.findByCustomerId(customerId).orElseGet(()->{CustomerCrmProfile profile=new CustomerCrmProfile();profile.setCustomerId(customerId);return profiles.saveAndFlush(profile);});}
 private CustomerCrmNote requireNote(UUID customerId,UUID noteId){CustomerCrmNote note=notes.findById(noteId).orElseThrow(()->new ApplicationException(HttpStatus.NOT_FOUND,"CRM note not found"));if(!note.getProfile().getCustomerId().equals(customerId))throw new ApplicationException(HttpStatus.NOT_FOUND,"CRM note not found");return note;}
 private void requireVersion(Long actual,Long expected){if(expected==null||!Objects.equals(actual,expected))throw new ApplicationException(HttpStatus.CONFLICT,"CRM resource was changed; refresh and try again");}private String normalizeSearch(String value){return value==null||value.isBlank()?null:value.trim();}
}
