package com.game_manager.gm.events;

public enum DomainEventType {
    AUTH_SESSION_STARTED,
    AUTH_SESSION_ENDED,
    USER_CREATED,
    USER_PROFILE_UPDATED,
    USER_PASSWORD_CHANGED,
    USER_DEACTIVATED,
    USER_DELETED,
    USER_RESTORED,
    RESERVATION_CREATED,
    RESERVATION_STATUS_CHANGED,
    ORDER_CREATED,
    ORDER_STATUS_CHANGED
}
